name: Patch

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download apkeep
        uses: robinraju/release-downloader@v1.10
        with:
          repository: EFForg/apkeep
          tag: 0.16.0
          fileName: apkeep-x86_64-unknown-linux-gnu

      - name: Download apktool
        uses: robinraju/release-downloader@v1.10
        with:
          repository: iBotPeaches/Apktool
          tag: v2.9.3
          fileName: apktool_2.9.3.jar

      - name: Download libEmden
        uses: robinraju/release-downloader@v1.10
        with:
          repository: not-rzwei/libEmden
          tag: 1.0.0
          fileName: libEmden.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tools
        run: |
          mv apktool_2.9.3.jar apktool.jar
          mv apkeep-x86_64-unknown-linux-gnu apkeep
          chmod +x apkeep
          tar -xzf libEmden.tar.gz
          ls

      - name: Download APK
        env:
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
        run: |
          ./apkeep -a $PACKAGE_NAME .
          unzip -q $PACKAGE_NAME.xapk -d $PACKAGE_NAME
          java -jar apktool.jar -q -f d $PACKAGE_NAME
          ls
